### ISSUE TITLE
7-Days-HTML-Learning-Plan-for-Beginners Tracker

### ISSUE THREAD

**Issue by jpllbn** [labanonpaul/14-Day-HTML-Learning-Plan-for-Beginners#1]
- [x] Day 1 - Introduction to HTML Basics
- [x] Day 2 - Lists and Links in HTML
- [x] Day 3 -  HTML Forms
- [x] Day 4 - HTML Multimedia
- [ ] Day 5 - HTML Semantic Elements
- [ ] Day 6 - HTML Tables
- [ ] Day 7 - HTML Accessibility
